
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rafa
 */
public class FrmPaises extends javax.swing.JFrame {

    /**
     * Creates new form FrmPaises
     */
    public FrmPaises() {
        initComponents();
        llenarComboArreglo();
        llenarComboObjetos();
    }

    private void llenarComboArreglo() {
        String[] paises = {"Argentina", "Peru", "Mexico", "Venezuela"};
        for (String pais : paises) {
            cmbPaisB.addItem(pais);
        }
    }

    private void llenarComboObjetos() {
        ArrayList<Pais> listaP = new ArrayList<Pais>();
        Pais p1 = new Pais("España", 1);
        Pais p2 =new Pais("Holanda", 2);
        Pais p3=new Pais("Guatemala", 3);
        listaP.add(p1);
        listaP.add(p2);
        listaP.add(p3);
        for (Pais aux: listaP){
            cmbPaisC.addItem(aux);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbPaisA = new javax.swing.JComboBox<>();
        btnSeleccionA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSeleccionado = new javax.swing.JTextField();
        cmbPaisB = new javax.swing.JComboBox<>();
        btnSeleccionB = new javax.swing.JButton();
        cmbPaisC = new javax.swing.JComboBox<>();
        btnSeleccionC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbPaisA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ecuador", "UKrania", "Canadá", "Brasil", "Philipinas" }));
        cmbPaisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPaisAActionPerformed(evt);
            }
        });

        btnSeleccionA.setText("Escoger A");
        btnSeleccionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionAActionPerformed(evt);
            }
        });

        jLabel1.setText("Item Seleccionado");

        btnSeleccionB.setText("Escoger B");
        btnSeleccionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionBActionPerformed(evt);
            }
        });

        btnSeleccionC.setText("Escoger C");
        btnSeleccionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cmbPaisA, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSeleccionA))
                        .addComponent(jLabel1)
                        .addComponent(txtSeleccionado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbPaisC, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE)
                            .addComponent(cmbPaisB, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSeleccionB)
                            .addComponent(btnSeleccionC))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPaisA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPaisB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPaisC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionC))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPaisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPaisAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPaisAActionPerformed

    private void btnSeleccionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionAActionPerformed
        // TODO add your handling code here:
        String item =cmbPaisA.getSelectedItem().toString();
        txtSeleccionado.setText(item);
    }//GEN-LAST:event_btnSeleccionAActionPerformed

    private void btnSeleccionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionBActionPerformed
        // TODO add your handling code here:
        String item = cmbPaisB.getSelectedItem().toString();
        txtSeleccionado.setText(item);
    }//GEN-LAST:event_btnSeleccionBActionPerformed

    private void btnSeleccionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionCActionPerformed
        // TODO add your handling code here:
        Pais aux=(Pais) cmbPaisC.getSelectedItem();
        txtSeleccionado.setText(aux.getNombre());
    }//GEN-LAST:event_btnSeleccionCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPaises.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPaises().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionA;
    private javax.swing.JButton btnSeleccionB;
    private javax.swing.JButton btnSeleccionC;
    private javax.swing.JComboBox<String> cmbPaisA;
    private javax.swing.JComboBox<String> cmbPaisB;
    private javax.swing.JComboBox<Object> cmbPaisC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSeleccionado;
    // End of variables declaration//GEN-END:variables
}
