/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author WINDOWS
 */
public class subGraficarMagnitudSismica_Tecnico extends javax.swing.JFrame {

    /**
     * Creates new form subGraficarMagnitudSismica_Tecnico
     */
    public subGraficarMagnitudSismica_Tecnico() {
        initComponents();
        btnGenerarGrafico.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
        controlador.ControladorEventos.graficarMagnitudSismica(jpGRAFICA);
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateDia = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cbxEstacion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        dateInicio = new com.toedter.calendar.JDateChooser();
        dateFin = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        optMostrarGraficoDiario = new javax.swing.JRadioButton();
        optMostrarGraficoEstacion = new javax.swing.JRadioButton();
        optCompararMagnitudes = new javax.swing.JRadioButton();
        btnGenerarGrafico = new javax.swing.JButton();
        btnInsertarReporte = new javax.swing.JButton();
        btnExportarPDF = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jpGRAFICA = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GRAFICAR MAGNITUD SISMICA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 640, 90));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Seleccionar Día:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));
        jPanel1.add(dateDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 190, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Seleccionar Estación:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jPanel1.add(cbxEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 190, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Rango de dias:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 100, -1));
        jPanel1.add(dateInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));
        jPanel1.add(dateFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 90, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("OPCIONES");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        optMostrarGraficoDiario.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        optMostrarGraficoDiario.setText("Mostrar grafico diario");
        optMostrarGraficoDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optMostrarGraficoDiarioActionPerformed(evt);
            }
        });
        jPanel1.add(optMostrarGraficoDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        optMostrarGraficoEstacion.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        optMostrarGraficoEstacion.setText("Mostrar grafico por estacion");
        jPanel1.add(optMostrarGraficoEstacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        optCompararMagnitudes.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        optCompararMagnitudes.setText("Comparar Magnitudes entre dias");
        jPanel1.add(optCompararMagnitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        btnGenerarGrafico.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGenerarGrafico.setText("GENERAR GRAFICO");
        jPanel1.add(btnGenerarGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        btnInsertarReporte.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnInsertarReporte.setText("INSERTAR REPORTE");
        jPanel1.add(btnInsertarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        btnExportarPDF.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnExportarPDF.setText("EXPORTAR PDF");
        jPanel1.add(btnExportarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton4.setText("REGRESAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setText("GRAFICO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jpGRAFICA.setBackground(new java.awt.Color(153, 153, 153));
        jpGRAFICA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpGRAFICALayout = new javax.swing.GroupLayout(jpGRAFICA);
        jpGRAFICA.setLayout(jpGRAFICALayout);
        jpGRAFICALayout.setHorizontalGroup(
            jpGRAFICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jpGRAFICALayout.setVerticalGroup(
            jpGRAFICALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );

        jPanel1.add(jpGRAFICA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 600, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optMostrarGraficoDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optMostrarGraficoDiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optMostrarGraficoDiarioActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       VentanaTecnico vant=new VentanaTecnico();
        vant.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subGraficarMagnitudSismica_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subGraficarMagnitudSismica_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subGraficarMagnitudSismica_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subGraficarMagnitudSismica_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subGraficarMagnitudSismica_Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnExportarPDF;
    public javax.swing.JButton btnGenerarGrafico;
    public javax.swing.JButton btnInsertarReporte;
    private javax.swing.JComboBox<String> cbxEstacion;
    public com.toedter.calendar.JDateChooser dateDia;
    public com.toedter.calendar.JDateChooser dateFin;
    public com.toedter.calendar.JDateChooser dateInicio;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpGRAFICA;
    public javax.swing.JRadioButton optCompararMagnitudes;
    public javax.swing.JRadioButton optMostrarGraficoDiario;
    public javax.swing.JRadioButton optMostrarGraficoEstacion;
    // End of variables declaration//GEN-END:variables
}
