
package vista;

import com.mongodb.MongoClient;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Date;
import javax.swing.JFileChooser;
import org.bson.Document;

public class SubVMedirIndiceExplosividadVolcanica_Cientifico extends javax.swing.JFrame {

    /**
     * Creates new form SubVMedirIndiceExplosividadVolcanica_Cientifico
     */
    public SubVMedirIndiceExplosividadVolcanica_Cientifico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAlturaColumna = new javax.swing.JTextField();
        txtVolumenExpulsado = new javax.swing.JTextField();
        txtDuracionExplocion = new javax.swing.JTextField();
        btnGenerarDatos = new javax.swing.JButton();
        btnVerVEI = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtResultadoVEI = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnMigrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 360));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INDICE DE EXPLOSIVIDAD VEI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 580, 80));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setText("Altura Columna (km):");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setText("Volumen Expulsado (m^3):");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setText("Duracion explocion (h):");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));
        jPanel1.add(txtAlturaColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 210, -1));
        jPanel1.add(txtVolumenExpulsado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 210, -1));
        jPanel1.add(txtDuracionExplocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 210, -1));

        btnGenerarDatos.setBackground(new java.awt.Color(255, 0, 0));
        btnGenerarDatos.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGenerarDatos.setText("GENERAR DATOS");
        jPanel1.add(btnGenerarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        btnVerVEI.setBackground(new java.awt.Color(255, 0, 0));
        btnVerVEI.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnVerVEI.setText("VER VEI");
        jPanel1.add(btnVerVEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setText("VEI:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));
        jPanel1.add(txtResultadoVEI, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 190, -1));

        btnGuardar.setBackground(new java.awt.Color(255, 0, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGuardar.setText("GUARDAR");
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        btnMigrar.setBackground(new java.awt.Color(255, 0, 0));
        btnMigrar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnMigrar.setText("MIGRAR");
        btnMigrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMigrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMigrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel6.setText("ESTADO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));
        jPanel1.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 410, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaCientifico subv=new VentanaCientifico();
        subv.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMigrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMigrarActionPerformed
       JFileChooser fileChooser = new JFileChooser();
    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        File archivo = fileChooser.getSelectedFile();

        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            MongoClient mongoClient = new MongoClient("localhost", 27017);
            MongoDatabase database = mongoClient.getDatabase("sistema_volcanico");
            MongoCollection<Document> collection = database.getCollection("vei_registros");

            int contador = 0;
            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(";");
                if (datos.length >= 3) {
                    try {
                        double alturaColumna = Double.parseDouble(datos[0].trim());
                        double volumenExpulsado = Double.parseDouble(datos[1].trim());
                        double duracionExplosion = Double.parseDouble(datos[2].trim());

                        Document doc = new Document("altura_columna_km", alturaColumna)
                            .append("volumen_expulsado_m3", volumenExpulsado)
                            .append("duracion_explosion_h", duracionExplosion)
                            .append("fecha", new Date());

                        collection.insertOne(doc);
                        contador++;

                    } catch (NumberFormatException nfe) {
                        System.err.println("⚠️ Error en línea: " + linea);
                        continue; // salta al siguiente registro
                    }
                }
            }
            mongoClient.close();
            lblEstado.setText("✅ Migración completada: " + contador + " registros guardados.");
            lblEstado.setForeground(Color.GREEN);

        } catch (Exception e) {
            e.printStackTrace(); // muestra error en consola
            lblEstado.setText("❌ Error en la migración: " + e.getMessage());
            lblEstado.setForeground(Color.RED);
        }
    }
    }//GEN-LAST:event_btnMigrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubVMedirIndiceExplosividadVolcanica_Cientifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubVMedirIndiceExplosividadVolcanica_Cientifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubVMedirIndiceExplosividadVolcanica_Cientifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubVMedirIndiceExplosividadVolcanica_Cientifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubVMedirIndiceExplosividadVolcanica_Cientifico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGenerarDatos;
    public javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMigrar;
    private javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnVerVEI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblEstado;
    public javax.swing.JTextField txtAlturaColumna;
    public javax.swing.JTextField txtDuracionExplocion;
    public javax.swing.JTextField txtResultadoVEI;
    public javax.swing.JTextField txtVolumenExpulsado;
    // End of variables declaration//GEN-END:variables
}
